// SPDX-FileCopyrightText: Copyright (c) 2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! gRPC protocol crate for the `nvnmosd` NMOS daemon.
//!
//! The `nvnmos.daemon.v1` package contains the full service surface,
//! generated by `tonic-build` from `proto/nvnmosd.proto`. The design
//! rationale and per-RPC semantics live in
//! [`doc/designs/nvnmosd/README.md`](../../../doc/designs/nvnmosd/README.md).

pub mod v1 {
    tonic::include_proto!("nvnmos.daemon.v1");
}

pub use v1::*;
