name: Deploy Doxygen Documentation to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Doxygen
      run: sudo apt update && sudo apt install -y doxygen graphviz

    - name: Generate Documentation
      run: cd src && doxygen ../Doxyfile && mv html ../public

    - name: Upload Documentation Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
